# The URL the site will be built for
base_url = "https://peterkos.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Important :)
theme = "zola-paper"

# Site config
title = "Peter Kos"
description = "I write orchestral music, hammer out lots of code, and spend too much time watching cat videos."

# taxonomies = [
#     { name = "categories" },
#     { name = "tags" },
# ]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]

# hyde_theme = "theme-base-0d"
hyde_sticky = false

hyde_links = [
    {url = "https://github.com/peterkos", name = "GitHub"},
    {url = "https://twitter.com/pkos91", name = "Twitter"},
    {url = "https://linkedin.com/in/peter-kos", name = "LinkedIn"},
    {url = "https://bit.ly/peterkos-music-portfolio-2021", name = "Music Portfolio"}
]
