
base_url = "https://peterkos.me"
compile_sass = true
build_search_index = true

theme = "apollo"
title = "Peter Kos"


[markdown]
bottom_footnotes = true
highlight_code = true
highlight_theme = "duskfox-dark"
extra_syntaxes_and_themes = ["highlight_themes"]
# highlight_themes_css = [
#     { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
#     { theme = "ayu-dark", filename = "syntax-theme-light.css" },
# ]


[extra]
theme = "toggle" # light, dark, auto, toggle
mathjax = true
mathjax_dollar_inline_enable = true
socials = [
    { name = "mastodon", url = "https://iosdev.space/@peterkos", icon = "mastodon" },
    { name = "github", url = "https://github.com/peterkos/", icon = "github" },
]
menu = [
    # { name = "/posts", url = "/posts", weight = 1 },
    { name = "/talks", url = "/talks", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/résumé", url = "/peter-kos-resume.pdf", weight = 3 },
    { name = "/about", url = "/about", weight = 4 }
]
stylesheets = [
    "custom.css"
]

[extra.analytics]
enabled = true

[extra.analytics.umami]
website_id = "99946fb4-dcf8-4aa9-a7b0-e2d0876fb29c"
host_url = "https://umami.peterkos.me"
